libc :=

libc += getopt.o
libc += string/strcmp.o
libc += string/strcpy.o
libc += string/strlcpy.o
libc += string/strlcat.o
libc += string/strncmp.o
libc += string.o
libc += printf.o
libc += pthread.o
libc += dir.o
libc += file.o
libc += libc.o
libc += dlfcn.o
libc += time.o
libc += ctype.o
libc += signal.o
libc += mman.o
libc += qsort.o
