#
# Copyright (C) 2017 XLAB, Ltd.
# Copyright (C) 2018 Waldemar Kozaczuk
#
# This work is open source software, licensed under the terms of the
# BSD license as described in the LICENSE file in the top-level directory.
#
# This Docker file defines a container intended to build, test and publish
# OSv kernel as well as many applications ...
#
ARG FEDORA_VERSION=29
FROM fedora:${FEDORA_VERSION}

RUN yum install -y git python3 file which

#
# PREPARE ENVIRONMENT
#

# - prepare directories
RUN mkdir /git-repos /result

# - clone OSv
WORKDIR /git-repos
ARG GIT_ORG_OR_USER=cloudius-systems
RUN git clone https://github.com/${GIT_ORG_OR_USER}/osv.git
WORKDIR /git-repos/osv
RUN git submodule update --init --recursive

# - install all required packages
RUN scripts/setup.py

# - install Capstan
RUN wget https://github.com/cloudius-systems/capstan/releases/latest/download/capstan -O /usr/local/bin/capstan
RUN chmod u+x /usr/local/bin/capstan

CMD /bin/bash

#
# NOTES
#
# Build the container example:
# docker build -t osv/builder-fedora -f Dockerfile.builder-fedora .
#
# Build the container based of specific Fedora version and git repo owner (if forked) example:
# docker build -t osv/builder-fedora -f Dockerfile.builder-fedora --build-arg FEDORA_VERSION=31 --build-arg GIT_ORG_OR_USER=a_user .
#
# Run the container FIRST time example:
# docker run -it --privileged osv/builder-fedora
# 
# To restart:
# docker restart ID (from docker ps -a) && docker attach ID
#
# To open in another console
# docker exec -it ID /bin/bash
