#!/bin/sh

# This is here to help cope with the transition period that the distro
# use for openssl-1.0 to openssl-1.1
if [ -f /usr/include/openssl/opensslv.h ]; then
    has_new_openssl=$(grep "OpenSSL 1.1" /usr/include/openssl/opensslv.h)
fi
if [ "$has_new_openssl"x != "x" ]; then
    echo "OpenSSL 1.1 header detected."
    echo "On Fedora >= 26 please use the compat headers by doing:"
    echo ""
    echo "    dnf install --allowerasing compat-openssl10-devel -y"
    echo ""
    exit 1
fi
exit 0
