#!/bin/sh

set -e

build=./scripts/build-vm-img

$build cloudius/osv           default                   "OSv with shell for users"
$build cloudius/osv-cassandra cassandra,httpserver      "Apache Cassandra/OSv"
$build cloudius/osv-tomcat    tomcat,httpserver         "Apache Tomcat/OSv"
$build cloudius/osv-iperf     iperf,httpserver          "iperf/OSv"
$build cloudius/osv-memcached-opt osv-memcached,httpserver "OSv memcached server (optimized)"
