#!/bin/sh

program=$(basename $0)

set -e

if [ $# -lt 2 ]; then
    echo "usage: $program [name] [image] [description]"
    exit 1
fi

name=$1
image=$2
description=$3

version=$(scripts/osv-version.sh)
now=$(date +"%Y-%m-%dT%R:%S")

out=build/capstan/$name
qemuimage=build/release/osv.qcow2
vboximage=build/release/osv.vdi
gceimage=build/release/osv.tar.gz
vmwimage=build/release/osv.vmdk
index=$out/index.yaml
build="scripts/build image=$image"

mkdir -p $out

echo "==> Building '$name'..."

echo "format_version: 1" > $index
echo "version: $version" >> $index
echo "created: $now" >> $index
echo "description: $description" >> $index
echo "build: $build" >> $index

$build

# Generate QEMU image
scripts/convert qcow2-old
scripts/convert vdi
scripts/convert vmdk

# Generate GCE image
scripts/gen-gce-tarball.sh

gzip < $qemuimage > $out/$(basename $name).qemu.gz
gzip < $vboximage > $out/$(basename $name).vbox.gz
gzip < $vmwimage  > $out/$(basename $name).vmw.gz

gce_url_file=$out/$(basename $name).gce
gce_tar_ball=$out/$(basename $name).gce.tar.gz
echo "gs://osv/$version/$(basename $name).gce.tar.gz" > $gce_url_file
gzip <$gce_url_file > $gce_url_file.gz
rm -f $gce_url_file  $gce_tar_ball
mv -f $gceimage $gce_tar_ball

echo "==> '$name' image built to '$out'."
