#!/bin/sh

set -e

version=$(git describe --tags --long)

make qcow2

image=build/release/usr.qcow2

url=http://cloudius.artifactoryonline.com/cloudius/simple/osv-releases/osv-$version.qcow2
user=$USER

curl --progress-bar -X PUT --data-binary @$image $url -u $user -p
