#!/bin/bash

TEMP=`getopt -o dm:c:e: --long debug,memsize:,vcpus:,execute: -n "$0" -- "$@"`
if [ $? != 0 ]
then
	echo "Usage: $0 [-d] [-m memsize] [-c vcpus] [-e commandline]" >&2
	exit 1
fi
eval set -- "$TEMP"

# default values that can be overriden by command-line arguments
v=release
memsize=1G
vcpus=4
execute=""

while true
do
	case "$1" in
	-d|--debug)
		v=debug
		shift;;
	-m|--memsize)
		memsize=$2
		shift 2;;
	-c|--vcpus)
		vcpus=$2
		shift 2;;
	-e|--execute)
		execute=$2
		shift 2;;
	--)
		shift
		break;;
	esac
done

test -n "$execute" && scripts/imgedit.py setargs build/$v/loader.img $execute

qemu-system-x86_64 \
	-vnc :1 \
	-enable-kvm \
	-gdb tcp::1234,server,nowait \
	-cpu host,+x2apic \
	-m $memsize \
	-smp $vcpus \
	-chardev stdio,mux=on,id=stdio \
	-mon chardev=stdio,mode=readline,default \
	-device isa-serial,chardev=stdio \
	-device virtio-net-pci \
	-drive file=build/$v/loader.img,if=virtio,cache=unsafe \
	-drive file=build/$v/usr.img,if=virtio,cache=unsafe
