/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_osv_OSvGCMonitor */

#ifndef _Included_io_osv_OSvGCMonitor
#define _Included_io_osv_OSvGCMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_osv_OSvGCMonitor
 * Method:    NotifyOSv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_osv_OSvGCMonitor_NotifyOSv
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
